server:
  port: 8080
  host: 0.0.0.0
  workers: 4

  headers:
    - key: x-forwarded-for
      value: $ip

  upstreams:
    - id: server1
      host: 127.0.0.1
      port: 8081

    - id: server2
      host: 127.0.0.1
      port: 8082

  paths:
    - path: /api
      upstreams:
        - server1

    - path: /apiV2
      upstreams:
        - server2
        - server1
